### ISSUE TITLE
Readme file is not comprehensive enough

### ISSUE THREAD

**Issue by f2015537** [systers/communities#117]
## Description
As a developer,
I need make the Readme file comprehensive,
so that new contributors can easily setup the web app on their system locally.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [README.md]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hours

**Comment by f2015537** [comment]
@Tharangi please assign this to me!

**Comment by f2015537** [comment]
## How can users get started with contributing to the project? 
  
Anyone can find an issue in the application, the issue is not limited to bugs but also includes UI enhancements, efficient codes or improved structure.  
  
The following procedure must be followed in order to solve an issue.    
  
* Check if the issue has already been reported, if not report the issue on Github.
* Ask one of the mentors to assign it you.  
* You can open an issue and tag it as free if you do not wish to solve it. 
* The issues marked free are open for you to solve, assign the issue to yourself before beginning the work on it. 
* Before you make a Pull request, make sure that there are no linting errors with the files you modified.

## Getting Started

#### Fork the Repository
On GitHub, navigate to the communities Repository.
In the top-right corner of the page, click Fork.

#### Clone the Repository
Now, navigate to the forked repository in your profile.
In the top-right corner of the page, you will find a green button with the text "Clone or download". Click on it.
Copy the link that appears in the popup.

Now, go to your terminal (if you are using a Linux platform) or git bash (if you are using a Windows platform) and execute this command

```
git clone URL
```

Replace URL with the copied url

or you can just,

Go to your terminal and execute this command

```
$ git clone https://github.com/YOUR_USERNAME/communities
```
Replace YOUR_USERNAME with your Github username.

### Installation
Head over to https://nodejs.org/en/ and download the LTS version of nodejs.
Run the following in your terminal to verfiy if node has been correctly installed.
```
$ node -v
$ npm  -v
```
There should be no errors if node was installed correctly.

Install all dependencies in package.json file. This can be done by navigating to the cloned communities directory in the command prompt/terminal/console and running the following commands:

```
$ cd communities
$ npm install
$ ng serve
```
to setup the Angular developmental server.

After the build completes, you can navigate to http://localhost:3000/ in your browser to check out the application. 

And, that's it, you are DONE. You have successfully setup the project.

The app will automatically reload if you change any of the source files.

**Comment by f2015537** [comment]
@Tharangi  it would look like this ^. Is this fine? Shall I start working?

**Comment by Tharangi** [comment]
yeah! :)
