### ISSUE TITLE
Fix responsiveness of buttons in calendar page

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#122]
## Description
As a user
I need fix the responsiveness of buttons in calendar page and align the buttons in one horizontal line

## Mocks
![screenshot from 2018-12-11 18-27-21](https://user-images.githubusercontent.com/25412153/49802293-838daf80-fd72-11e8-9b2c-997367435555.png)

### Update [Required]
- [ ] calendar.component.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1.5 hours 
(Code is in master branch)

**Comment by debck** [comment]
I would like to work on this. Please assign me this.
@anumehaagrawal
