### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by BaaniLeen** [systers/communities#17]
## Description
As a Member,
I need to update the README file,
so that I can make it easier for others to understand the contents of this repository.

### Update [Required]
- [ ] [README.md]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours 

Can I work on this issue?

**Comment by anumehaagrawal** [comment]
@Tharangi  Can I work on this issue  if @BaaniLeen  has not been assigned and is not working on it

**Comment by Tharangi** [comment]
@BaaniLeen I will Assign this to @anumehaagrawal  as she will be working on this repository mostly in coming months.
