### ISSUE TITLE
Development of Header and Footer

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#20]
## Description
As a user,
I need develop the header and footer components

### Update [Required]
- [ ] Nav bar components
- [ ] Footer components

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours 
@Tharangi  Can you assign me this issue ?

**Comment by Tharangi** [comment]
Merged with #30
