### ISSUE TITLE
Create contact us page for the communities website

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#22]
## Description
As a user I need to develop a contact page 

## Mocks
![screenshot from 2018-05-16 10-27-04](https://user-images.githubusercontent.com/25412153/40097429-b3d18938-58f3-11e8-8115-4fd14082abd8.png)

### Update [Required]
- [ ] contact.component.html
- [ ] contact.component.scss

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 5 hours 
@Tharangi  Can you please assign me this ?

**Comment by Tharangi** [comment]
Assigned!
