### ISSUE TITLE
Create Home Page for the communities website

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#27]
## Description
As a user
I need to create a home page for the website
### Update [Required]
- [ ] home.component.html
- [ ] home.component.scss

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10-11 hours 
@kanmodi  @Tharangi  Can you assign me this issue ?

**Comment by Tharangi** [comment]
Assigned!

**Comment by Tharangi** [comment]
#8

**Comment by kanmodi** [comment]
Closed #27
