### ISSUE TITLE
Create communities section 

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#33]
## Description
As a user
I need to create the affinity groups (communities ) section in the website

### Update [Required]
- [ ] communities.component.html
- [ ] communities.component.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours 
@Tharangi @kanmodi Please assign me this issue

**Comment by Tharangi** [comment]
Assigned!

**Comment by Tharangi** [comment]
This was merged with #40
