### ISSUE TITLE
Creating a submittable contact form

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#34]
## Description
As a Systers community member
I should be able to submit a message request to Systers Admins
so that I can clarify my need. 

### Update [Required]
- [ ] contact.component.ts
- [ ] contact.component.html
@kanmodi  @Tharangi  Can you assign me this issue ?
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
16 hours

**Comment by kanmodi** [comment]
@anumehaagrawal Assigned!

**Comment by Tharangi** [comment]
This issue is already fixed and merged but without reference.
