### ISSUE TITLE
Create a calendar to view events

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#36]
## Description
As a Systers Community member,
I need to know the upcoming events,
so that I can join the events. 

### Update [Required]
- [ ] calendar.component.ts
- [ ] calendar.component.js
- [ ] calendar.js

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
12 hours 
@Tharangi  @kanmodi  Can you assign me this issue ?

**Comment by Tharangi** [comment]
Assigned!

**Comment by kanmodi** [comment]
Calendar added!
Closed #36
