### ISSUE TITLE
Fix the slider height in the Communities page

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#37]
## Description
As a Systers community member
I need to see the slider with a proper height
so that I can have a better user experience

## Mocks
![screenshot from 2018-06-04 21-15-31](https://user-images.githubusercontent.com/25412153/40927479-71fbbc56-683c-11e8-85a8-8e7f08e48d17.png)

### Update [Required]
- [ ] communities.component.html
- [ ]  communities.component.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours 
@Tharangi  @kanmodi  Can you assign me this ?

**Comment by Tharangi** [comment]
Assigned!

**Comment by Tharangi** [comment]
This issue is already merged but without reference.
