### ISSUE TITLE
Change the Systers Affinity from Tabs to Cards

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#39]
## Description
As a user
I need to change the view to cards

## Mocks
(Possibility of 4 cards in a row)
![screenshot from 2018-06-06 00-50-29](https://user-images.githubusercontent.com/25412153/41024767-c1766a86-698d-11e8-9d53-95f9f310a23b.png)

### Update [Required]
- [ ] communities.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours 
@Tharangi @kanmodi  Please assign me this issue

**Comment by kanmodi** [comment]
Assigned!
