### ISSUE TITLE
Add relevant images to Community Groups in Communities Page 

### ISSUE THREAD

**Issue by Tharangi** [systers/communities#43]
## Description
As a Systers Community member,
I need to see relevant images community group-wise in the Communities Page,
so that I can have a better user experience.

### Update [Required]
- [ ] communities.component.html
- [ ] communities.component.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1.5 hours

**Comment by kanmodi** [comment]
@anumehaagrawal will add images given by @may from the marketing team here. 
Closing #43

**Comment by kanmodi** [comment]
My bad. Still pending!
