### ISSUE TITLE
Adding upcoming events cards

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#44]
## Description
As a user
I need to add cards to display upcoming events

### Update [Required]
- [ ] home.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 hours 
@Tharangi @kanmodi  Can you please assign me this issue ?

**Comment by kanmodi** [comment]
Assigned!

**Comment by kanmodi** [comment]
Closed #44
