### ISSUE TITLE
Add Join us section in contact page

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#48]
## Description
As a user
I need add a join us section along with contact form

## Mocks
![screenshot from 2018-06-13 19-31-04](https://user-images.githubusercontent.com/25412153/41355982-56a9323e-6f40-11e8-8c50-55cff2ff5398.png)

### Update [Required]
- [ ] contact.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours 
@Tharangi  @kanmodi  Can you assign me this issue ?

**Comment by Tharangi** [comment]
Make sure to align the labels to left and the button to right as well in the contact form as discussed at the GitHub pages All Teams meeting today. :)

**Comment by kanmodi** [comment]
Join us section added.
Closed #48
