### ISSUE TITLE
Modify the javascript for the calendar to display all events

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#57]
## Description
As a user
I need to modify the js file
so that I can render all calendar events

### Update [Required]
- [ ] google_cal.js

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 
@Tharangi  @kanmodi  Please assign me this issue :)

**Comment by kanmodi** [comment]
Done! :)
