### ISSUE TITLE
Modify the upcoming events js

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#62]
## Description
As a user
I need to modify js to update upcoming events
### Update [Required]
- [ ] home.component.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes
@Tharangi  Please assign me this issue

**Comment by kanmodi** [comment]
Assigned!

**Comment by Tharangi** [comment]
This issue is already merged but without reference.
