### ISSUE TITLE
Adding multiple google calendars in the angular calendar

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#64]
## Description
As a user
I need to add multiple google calendars
### Update [Required]
- [ ] google_cal.js

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 hours 
@Tharangi  @kanmodi  Please assign me this issue :)

**Comment by kanmodi** [comment]
Assigned :)
