### ISSUE TITLE
Create Home Page of Celebration

### ISSUE THREAD

**Issue by shreyateeza** [systers/communities#8]
## Description
As a Systers Community member,
I want to create a home page of Celebration,
so that I can get notified about the -
1. The latest ten events that will be happening
2. An area that describes how to join the mailing list
3. Overview of the Systers Communities

## Mocks
![celebration-home page](https://user-images.githubusercontent.com/30488330/37596110-17d85e0a-2ba1-11e8-8054-dd30225cd782.png)

## Update [Required]
- [ ] Add a mock for the 10 most current events displayed on the Home Page.
- [ ] Create a UML diagram to show the interactions from the initial Calendar integration to the Home Page.
- [ ] Include Overview of Systers Communities

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by shreyateeza** [comment]
I am working on this issue. :smile:

**Comment by shreyateeza** [comment]
@MeepyMay  Do I have to make the sign up form in this celebration home page to make people join it or provide a link to join the slack?
If latter is the case then I have to send them invitation to join the systers-opensource slack group or systers slack group?

**Comment by shreyateeza** [comment]
@MeepyMay @prachi1210 please let me know.

**Comment by MeepyMay** [comment]
This is a valid issue from GSoC18 Ideas.

**Comment by MeepyMay** [comment]
@shreyateeza I'm a little confused on the question and adjusted some of the wording in the original issue.

We're trying to provide a temporary solution with /celebration GH page. This is an informational site to display information about events and Systers communities since Portal is currently not in production.

**Comment by Saichethan** [comment]
@MeepyMay is creating celebration page a separate task? if this is a single task it doesn't take 3 months so, please give me some more information about project

**Comment by BaaniLeen** [comment]
@Saichethan It is one of the tasks listed under the project gh-pages. :)
Am I correct @MeepyMay ? :)

**Comment by Saichethan** [comment]
If this is complete project then in that time limit we can make it PWA(Progressive Web App) + AMP(Accelerated Mobile Pages) also, so can you please give me some more insights about project
