### ISSUE TITLE
Optimisations

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#84]
## Description
As a user
I need to compress images , minify js and css.

### Update [Required]
- [ ] images , js , css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours 
@Tharangi @Rupinderwadali @kanmodi  Please assign me this issue

**Comment by anumehaagrawal** [comment]
@Tharangi I will be working on this

**Comment by kanmodi** [comment]
Closed #84
