### ISSUE TITLE
Maintain consistent font size

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#85]
## Description
As a user
I need maintain consistent font size throughout
### Update [Required]
- [ ] style.css
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

@Tharangi @kanmodi @Rupinderwadali  Please assign me this issue

## Estimation
[INSERT NUMBER HERE] hours

**Comment by Tharangi** [comment]
#83
