### ISSUE TITLE
Add favicon.ico 

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#96]
## Description
As a user
I need add a favicon.ico

### Update [Required]
- [ ] favicon.ico
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours 
@Tharangi  @Rupinderwadali @kanmodi  Please assign me this issue

**Comment by kanmodi** [comment]
Assigned!

**Comment by anumehaagrawal** [comment]
@Tharangi  I will work on this

**Comment by sarnava1** [comment]
@anumehaagrawal are you still working on this? Can anyone here please help me with the local installation of this project?

**Comment by kanmodi** [comment]
@sarnava1 Pull Request #113 fixes this

**Comment by sarnava1** [comment]
@kanmodi Okay!!

**Comment by f2015537** [comment]
@sarnava1  you need to have angular cli installed on your system. Then navigate to you cloned repository and install dependencies by npm install. Then hit ng serve.

**Comment by f2015537** [comment]
@sarnava1 if you're still facing issues contact me on the slack group.

**Comment by sarnava1** [comment]
Thanks a lot @f2015537. If the problem persists I will surely contact you in the slack group.

**Comment by Tharangi** [comment]
Reopening as the PR is not closed yet.

**Comment by f2015537** [comment]
@Tharangi is this still available? Can I work on this?
