### ISSUE TITLE
Update footer according to marketing team guidelines

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/communities#97]
## Description
As a user
I need update the footer according to marketing team wireframe

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] footer.component.html
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours 
@Tharangi @Rupinderwadali @kanmodi  Please assign me this issue

**Comment by kanmodi** [comment]
Assigned!
